Show 'okay' message and include elapsed time at execution end.

diff --git a/sla b/sla
--- a/sla
+++ b/sla
@@ -6,6 +6,7 @@ RULES_FILE="build.sla"
 if [ -t 1 ]; then
     # Our output is not being redirected, so we can use colors.
     C_RED="\033[1;31m"
+    C_GREEN="\033[1;32m"
     C_RESET="$(tput sgr0)"
 fi
 
@@ -22,6 +23,13 @@ msg_debug () {
 die () {
     printf "${C_RED}%s$C_RESET\n" "$*" >&2
     exit 2
+}
+
+#
+# Print okay message to stdout
+#
+okay () {
+    printf "${C_GREEN}%s$C_RESET\n" "$*" >&2
 }
 
 #
@@ -139,6 +147,7 @@ msg_debug "RULE: $RULE"
 msg_debug "PARAMS:" "$@"
 
 # Run in subshell so get back exit code if execution fails with "set -e"
+TIME_START="$(date +"%s")"
 (
     # Jump to project root
     cd "$PROJ_ROOT"
@@ -156,6 +165,16 @@ msg_debug "PARAMS:" "$@"
 )
 EXIT_CODE=$?
 set +x
+TIME_END="$(date +"%s")"
+
+SECONDS=$(( TIME_END - TIME_START ))
+HOURS=$(( SECONDS / 3600))
+SECONDS=$(( SECONDS % 3600))
+MINUTES=$(( SECONDS / 60))
+SECONDS=$(( SECONDS % 60))
+ELAPSED_TIME="${HOURS}h ${MINUTES}m ${SECONDS}s"
 if [ $EXIT_CODE -ne 0 ]; then
-    die "Execution of rule '$RULE' failed with exitcode $EXIT_CODE"
+    die "Execution of rule '$RULE' failed with exitcode $EXIT_CODE. Duration: $ELAPSED_TIME"
+else
+    okay "Execution of rule '$RULE' succeeded with exitcode $EXIT_CODE. Duration: $ELAPSED_TIME"
 fi
