Shellcheck lint fixes.

diff --git a/sla b/sla
--- a/sla
+++ b/sla
@@ -6,29 +6,21 @@ RULES_FILE="rules.sla"
 if [ -t 1 ]; then
     # Our output is not being redirected, so we can use colors.
     C_RED="\033[1;31m"
-    C_GREEN="\033[1;32m"
-    C_YELLOW="\033[1;33m"
-    C_BLUE="\033[1;34m"
-    C_PURPLE="\033[1;35m"
-    C_CYAN="\033[1;36m"
-    C_WHITE="\033[1;37m"
     C_RESET="$(tput sgr0)"
 fi
-
-C_EXEC_RULE="$C_WHITE"
 
 #
 # Display debug message if FLAG_DEBUG is set (-d, --debug)
 #
 msg_debug () {
-    [ $FLAG_DEBUG -eq 1 ] && echo "DEBUG: $*" >&2
+    [ "$FLAG_DEBUG" -eq 1 ] && echo "DEBUG: $*" >&2
 }
 
 #
 # Print error message to stderr and exit with code 2
 #
 die () {
-    printf "${C_RED}$*${C_RESET}\n" >&2
+    printf "${C_RED}%s$C_RESET\n" "$*" >&2
     exit 2
 }
 
@@ -77,7 +69,7 @@ find_project_root () {
             break
         else
             # Go one dir up
-            PROJ_ROOT="$(realpath $PROJ_ROOT/..)"
+            PROJ_ROOT="$(realpath "$PROJ_ROOT"/..)"
         fi
     done
 }
@@ -86,7 +78,7 @@ find_project_root () {
 # Print a list of rules found in the rules file
 #
 get_rules () {
-    egrep '^.*\s?\()\s?\{' "$PROJ_ROOT/$RULES_FILE" | sed "s/^\(.*\)[[:space:]]*(.*/\\1/"
+    grep -E '^.*\s?\()\s?\{' "$PROJ_ROOT/$RULES_FILE" | sed "s/^\(.*\)[[:space:]]*(.*/\\1/"
 }
 
 # List rules found in the rules found
@@ -103,24 +95,27 @@ FLAG_DEBUG=0
 FLAG_VERBOSE=0
 RULE=""
 
-case "$1" in
-    "-h" | "--help")
-        usage
-        ;;
-    "--version")
-        version
-        ;;
-    "-d" | "--debug")
-        FLAG_DEBUG=1
-        shift
-        ;;
-    "-v" | "--verbose")
-        FLAG_VERBOSE=1
-        shift
-        ;;
-    *)
-        ;;
-esac
+while true; do
+    case "$1" in
+        "-h" | "--help")
+            usage
+            ;;
+        "--version")
+            version
+            ;;
+        "-d" | "--debug")
+            FLAG_DEBUG=1
+            shift
+            ;;
+        "-v" | "--verbose")
+            FLAG_VERBOSE=1
+            shift
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
 
 PROJ_ROOT="$(find_project_root)"
 if [ -z "$PROJ_ROOT" ]; then
@@ -134,7 +129,6 @@ fi
 
 RULE="$1"
 shift;
-PARAMS=$*
 
 # Check that the requested rule exists
 get_rules | grep "$RULE" > /dev/null || die "Rule '$RULE' not found"
@@ -142,7 +136,7 @@ get_rules | grep "$RULE" > /dev/null || die "Rule '$RULE' not found"
 msg_debug "FLAG_VERBOSE: $FLAG_VERBOSE"
 msg_debug "PROJ_ROOT: $PROJ_ROOT"
 msg_debug "RULE: $RULE"
-msg_debug "PARAMS: $*"
+msg_debug "PARAMS:" "$@"
 
 # Run in subshell so get back exit code if execution fails with "set -e"
 (
@@ -150,17 +144,18 @@ msg_debug "PARAMS: $*"
     cd "$PROJ_ROOT"
 
     # Source the rules file and execute the requested rule
-    . "$PROJ_ROOT/$RULES_FILE"
+    # shellcheck source=/dev/null
+    source "$PROJ_ROOT/$RULES_FILE"
 
     if [ "$FLAG_VERBOSE" -eq 1 ]; then
         # Show all commands being execute
         set -x
     fi
     set -e  # Fail on errors immediately
-    $RULE $*
+    $RULE "$@"
 )
 EXIT_CODE=$?
 set +x
 if [ $EXIT_CODE -ne 0 ]; then
-    printf "${C_RED}Exection of rule '$RULE' failed with exitcode $EXIT_CODE${C_RESET}\n"
+    die "Exection of rule '$RULE' failed with exitcode $EXIT_CODE"
 fi
